const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("pasargad", {
    addCheque: (data) => ipcRenderer.invoke("add-cheque", data),
    getCustomers: () => ipcRenderer.invoke("get-customers"),
    addCustomer: (data) => ipcRenderer.invoke("add-customer", data),
    getCheques: () => ipcRenderer.invoke("get-cheques"),
    findChequeByNumber: (chequeNo) => ipcRenderer.invoke("find-cheque-by-number", chequeNo),
    updateCheque: (payload) => ipcRenderer.invoke("update-cheque", payload),
    deleteCheque: (id) => ipcRenderer.invoke("delete-cheque", id),
    updateChequeStatus: (payload) => ipcRenderer.invoke("update-cheque-status", payload),
    confirmChequeStatus: (payload) => ipcRenderer.send("confirm-cheque-status", payload),
    getFiscalYears: () => ipcRenderer.invoke("get-fiscal-years"),
    createFiscalYear: (year) => ipcRenderer.invoke("create-fiscal-year", year),
    deleteFiscalYear: (year) => ipcRenderer.invoke("delete-fiscal-year", year),
    clearFiscalYear: (year) => ipcRenderer.invoke("clear-fiscal-year", year),
    createBackup: () => ipcRenderer.invoke("create-backup"),
    getBackupSettings: () => ipcRenderer.invoke("get-backup-settings"),
    chooseBackupSecondPath: () => ipcRenderer.invoke("choose-backup-second-path"),
    clearBackupSecondPath: () => ipcRenderer.invoke("clear-backup-second-path"),
    restoreBackup: (filePath) => ipcRenderer.invoke("restore-backup", filePath),
    getPrinters: () => ipcRenderer.invoke("get-printers"),
    getPrintSettings: () => ipcRenderer.invoke("get-print-settings"),
    savePrintSettings: (settings) => ipcRenderer.invoke("save-print-settings", settings),
    printCurrentPage: (settings) => ipcRenderer.invoke("print-current-page", settings),
    previewCurrentPage: (settings) => ipcRenderer.invoke("preview-current-page", settings),
    previewReport: (payload) => ipcRenderer.invoke("preview-report", payload),
    printReport: (payload) => ipcRenderer.invoke("print-report", payload),
    getAppearanceSettings: () => ipcRenderer.invoke("get-appearance-settings"),
    saveAppearanceSettings: (settings) => ipcRenderer.invoke("save-appearance-settings", settings),
    chooseAppearanceLogo: () => ipcRenderer.invoke("choose-appearance-logo"),
    getPrinters: () => ipcRenderer.invoke("get-printers"),
    getPrintSettings: () => ipcRenderer.invoke("get-print-settings"),
    savePrintSettings: (settings) => ipcRenderer.invoke("save-print-settings", settings),
    printCurrentPage: (settings) => ipcRenderer.invoke("print-current-page", settings),
    previewCurrentPage: (settings) => ipcRenderer.invoke("preview-current-page", settings),
    previewReport: (payload) => ipcRenderer.invoke("preview-report", payload),
    printReport: (payload) => ipcRenderer.invoke("print-report", payload),
    getAppearanceSettings: () => ipcRenderer.invoke("get-appearance-settings"),
    saveAppearanceSettings: (settings) => ipcRenderer.invoke("save-appearance-settings", settings),
    chooseAppearanceLogo: () => ipcRenderer.invoke("choose-appearance-logo"),
    onBackupBeforeExit: (callback) => ipcRenderer.on("request-backup-before-exit", () => callback()),
    finishBackupBeforeExit: (success) => ipcRenderer.send("backup-before-exit-done", !!success),
    hashText: (text) => String(text)
});
